Задание 6. Добавлена функциональность регистрации пользователя
gpb-it-factory/protasov-middle-service pull request #4
Opened 2024-06-14 19:35 UTC by tymillnyc

1. Добавлен контроллер регистрации пользователя.
2. Добавлена реализация сервиса регистрации пользователей.
3. Разработаны две реализации BackendClient: для реальной отправки запросов к backend-сервису и для работы с данными в изолированной памяти.
4. Реализованы тесты для проверки функциональности контроллера.

2024-06-22 13:31 UTC, vaganov-vadim requested changes
Классная работа. Есть пара вопросов и советов. Прошу обратить внимание на тесты, там есть пространство для улучшений.

2024-06-22 13:31 UTC, vaganov-vadim commented on src/main/java/ru/gazprombank/middle/client/InMemoryBackendClientImpl.java
> +public class InMemoryBackendClientImpl implements BackendClient {
Для таких штук хорошо бы делать настройку в конфигурации. Чтобы не перепутать реальный клиент и такой "моковый".

2024-06-22 13:31 UTC, vaganov-vadim commented on src/main/java/ru/gazprombank/middle/config/BackendClientConfig.java
> +    @ConditionalOnProperty(name = "backend.client-type", havingValue = "inMemory")
Предыдущий комментарий снят, отличная работа :)

2024-06-22 13:31 UTC, vaganov-vadim commented on src/main/java/ru/gazprombank/middle/repository/InMemoryUserRepository.java
> +public class InMemoryUserRepository implements UserRepository {
Вот это немного не понял. Репозиторий для чего?

2024-06-22 13:31 UTC, vaganov-vadim commented on src/test/java/ru/gazprombank/middle/controller/RegistrationControllerTests.java
> +        performPostRequest(userRegistrationRequest, HttpStatus.OK);
По тесту совершенно неясно, факт чего и какое поведение мы проверяли. Аналогично по тестам ниже. Давай проверять конкретный факт. "Регистрация нового пользователя" "Ошибка регистрации пользователя, если он уже зарегистрирован" и так далее.

2024-06-23 21:13 UTC, tymillnyc commented on src/main/java/ru/gazprombank/middle/repository/InMemoryUserRepository.java
> +public class InMemoryUserRepository implements UserRepository {
В нем хранятся данные пользователя (пока нет реальной бд). И он применяется в классе inMemoryBackendClientImpl для проверки, есть ли пользователь или нет, и сохранения пользователя в мапу

2024-06-25 16:15 UTC, vaganov-vadim requested changes
Привет. В целом всё ок, но по тестам надо чуть доработать.

2024-06-25 16:15 UTC, vaganov-vadim commented on src/test/java/ru/gazprombank/middle/controller/RegistrationControllerTests.java
> +        performPostRequest(userRegistrationRequest, HttpStatus.OK);
Вот тут как-то особо ничего не поменялось. Используй паттерн Arrange Act Assert. Рекомендация по названиям тестов выше.

2024-06-26 22:58 UTC, tymillnyc commented on src/test/java/ru/gazprombank/middle/controller/RegistrationControllerTests.java
> +        performPostRequest(userRegistrationRequest, HttpStatus.OK);
Убрал клиентов, теперь сервисы напрямую работают с бэкендом. Понял, что эта прослойка не нужна. И из-за нее сложнее было реализовать тесты. Также разобрался с тестами: поменял названия, сделал паттерн Arrange Act и Assert. Сейчас тесты кажутся более логичными

2024-06-29 09:27 UTC, vaganov-vadim approved these changes
Аппрув!

2024-06-29 11:52 UTC, merged